import {test,expect} from '@playwright/test';
import {adminRoutes} from '../../features/admin/routes';
const origin='http://127.0.0.1:3102';
test.beforeEach(async({context})=>{await context.addCookies([{name:'m5-admin-role',value:'super_admin',url:origin}]);});
for(const width of [390,768,1024,1440,1920])test(`admin overview and keyboard dialog at ${width}`,async({page},info)=>{
 await page.setViewportSize({width,height:1080});await page.goto(origin+'/admin');await expect(page.getByRole('heading',{name:'System health',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'System summary',exact:true})).toBeVisible();expect(await page.content()).not.toMatch(/private-admin-sentinel|controlled-admin-credential|x-elceo-internal-token/);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath(`admin-overview-${width}.png`),fullPage:true});
 await page.goto(origin+'/admin/commercial/users/controlled-user');const trigger=page.getByRole('button',{name:'Gift Focus Plan',exact:true});await trigger.click();const d=page.getByRole('dialog',{name:'Gift Focus Plan',exact:true});await expect(d.getByRole('textbox',{name:'user Id',exact:true})).toHaveValue('controlled-user');await d.getByRole('link',{name:'Read authoritative state'}).focus();await page.keyboard.press('Tab');await expect(d.getByRole('button',{name:'Close Gift Focus Plan'})).toBeFocused();await page.screenshot({path:info.outputPath(`admin-gift-${width}.png`),fullPage:true});await page.keyboard.press('Escape');await expect(trigger).toBeFocused();
});
test('all 23 destinations resolve with explicit degraded state',async({page,context})=>{await context.addCookies([{name:'m5-admin-state',value:'unavailable',url:origin}]);for(const [path,,heading]of adminRoutes){const response=await page.goto(origin+path.replace('[userId]','controlled-user'));expect(response?.status()).toBe(200);await expect(page.getByRole('heading',{name:heading,exact:true})).toBeVisible();expect(await page.content()).not.toContain('controlled-admin-credential');await expect(page.getByRole('button',{name:'Submit recorded change',exact:true})).toHaveCount(0);}});
for(const state of ['denied','malformed','unavailable'])test(`admin ${state} read state`,async({page,context})=>{await context.addCookies([{name:'m5-admin-state',value:state,url:origin}]);await page.goto(origin+'/admin');await expect(page.getByRole('status')).toContainText(state==='denied'?'Administrative permission denied':state==='malformed'?'Response cannot be displayed safely':'Administrative service unavailable');});
test('ordinary users cannot open Admin; unsupported price writes remain absent',async({page,context})=>{await context.addCookies([{name:'m5-admin-role',value:'user',url:origin}]);await page.goto(origin+'/admin');await expect(page).toHaveURL(/\/dashboard$/);await context.addCookies([{name:'m5-admin-role',value:'super_admin',url:origin}]);await page.goto(origin+'/admin/commercial/prices');await expect(page.getByRole('heading',{name:'Price changes are unavailable'})).toBeVisible();await expect(page.getByRole('button',{name:/Submit/})).toHaveCount(0);});
for(const verified of [false,true])test(`step-up ${verified?'receipt':'rejection'} never automatically performs a commercial action`,async({page,context})=>{
 if(verified)await context.addCookies([{name:'m5-admin-state',value:'verified',url:origin}]);const commands:string[]=[];page.on('request',r=>{if(r.url().endsWith('/api/admin-command')){expect(r.headers()['x-elceo-internal-token']).toBeUndefined();expect(r.headers()['idempotency-key']).toBeTruthy();commands.push(r.postDataJSON().command);}});
 await page.goto(origin+'/admin/commercial/users/controlled-user');await page.getByRole('button',{name:'Gift Focus Plan',exact:true}).click();const d=page.getByRole('dialog',{name:'Gift Focus Plan',exact:true});await d.getByRole('button',{name:'Request verification',exact:true}).click();await expect(d.getByRole('status')).toContainText('No verification is implied');await d.getByLabel('Step-up proof',{exact:true}).fill('private-submitted-proof');await d.getByRole('button',{name:'Verify proof',exact:true}).click();await expect(d.getByLabel('Step-up proof',{exact:true})).toHaveCount(0);expect(commands).toEqual(['challenge','verify']);expect(await page.content()).not.toMatch(/private-submitted-proof|private-proof-sentinel|controlled-admin-credential/);
 if(verified){await expect(d.getByRole('status')).toContainText('Final authorization');await d.getByRole('button',{name:'Submit verified change'}).click();await expect(d.getByRole('status')).toContainText('recorded result');expect(commands).toEqual(['challenge','verify','gift']);}else await expect(d.getByRole('status')).toContainText('Verification was not granted');await expect(d.getByRole('button',{name:'Request verification',exact:true})).toBeDisabled();
});
test('uncertain Admin request locks all actions after close without retry',async({page})=>{let calls=0;await page.route('**/api/admin-command',r=>{calls++;return r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({kind:'unavailable_degraded',status:503})});});await page.goto(origin+'/admin/commercial/users/controlled-user');await page.getByRole('button',{name:'Gift Focus Plan',exact:true}).click();const d=page.getByRole('dialog',{name:'Gift Focus Plan',exact:true});await d.getByRole('button',{name:'Request verification',exact:true}).click();await expect(d.getByRole('status')).toContainText('unconfirmed');await page.keyboard.press('Escape');await page.getByRole('button',{name:'Restrict user',exact:true}).click();await expect(page.getByRole('dialog',{name:'Restrict user',exact:true}).getByRole('button',{name:'Request verification',exact:true})).toBeDisabled();expect(calls).toBe(1);});
