import {test,expect} from '@playwright/test';
const origin='http://127.0.0.1:3102';
for(const width of [390,768,1024,1440,1920])test(`delivery settings and canonical navigation at ${width}`,async({page},info)=>{
 await page.setViewportSize({width,height:1080});await page.goto(origin+'/settings/notifications');await expect(page.getByRole('heading',{name:'Choose where context reaches you.'})).toBeVisible();await expect(page.getByText('unverified',{exact:true})).toBeVisible();await expect(page.getByText('degraded',{exact:true})).toBeVisible();expect(await page.content()).not.toMatch(/private-delivery-owner|private-provider-payload|excluded-address-field/);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await expect(page.getByRole('navigation',{name:'Application navigation'}).getByRole('link')).toHaveText(['Dashboard','Workspace','Journal','Portfolio','Analytics','Coaching']);await expect(page.getByRole('navigation',{name:'Account settings'})).toContainText('Notifications');await page.screenshot({path:info.outputPath(`delivery-settings-${width}.png`),fullPage:true});
 const trigger=page.getByRole('button',{name:/^Notifications/});await trigger.focus();await page.keyboard.press('Enter');const dialog=page.getByRole('dialog',{name:'Notification overview',exact:true});await expect(dialog.getByRole('link',{name:'Open notification inbox'})).toHaveAttribute('href','/notifications');await page.keyboard.press('Escape');await expect(trigger).toBeFocused();
});
test('notification preferences preserve authoritative motion and await readback',async({page})=>{await page.goto(origin+'/settings/notifications');await page.getByRole('checkbox',{name:'Email',exact:true}).check();const wait=page.waitForRequest(r=>r.url().endsWith('/api/account/preferences')&&r.method()==='PATCH');await page.getByRole('button',{name:'Save notification preferences'}).click();const r=await wait;expect(r.postDataJSON().motionIntensity).toBe('medium');expect(r.postDataJSON().notifications.email).toBe(true);expect(r.headers()['idempotency-key']).toBeTruthy();await expect(page.getByRole('button',{name:'Save notification preferences'})).toBeDisabled();});
for(const [label,endpoint] of [['Add delivery target','targets'],['Add channel subscription','subscriptions'],['Edit subscription','subscription-controlled'],['Request verification challenge','issue'],['Submit verification proof','consume']])test(`delivery mutation ${label}`,async({page})=>{
 await page.goto(origin+'/settings/notifications');await page.getByRole('button',{name:label,exact:true}).click();const d=page.getByRole('dialog',{name:label,exact:true});if(label==='Add delivery target')await d.getByLabel('Email address',{exact:true}).fill('new@example.test');if(label.includes('subscription'))await d.getByRole('combobox',{name:'Subscription state',exact:true}).selectOption('false');if(label==='Submit verification proof')await d.getByLabel('Verification proof',{exact:true}).fill('controlled-proof');
 const wait=page.waitForRequest(r=>['POST','PATCH'].includes(r.method())&&r.url().endsWith('/'+endpoint));await d.getByRole('button',{name:'Submit recorded change'}).click();const r=await wait;expect(r.headers()['idempotency-key']).toBeTruthy();expect(r.postDataJSON()).not.toHaveProperty('subjectId');await expect(d.getByRole('link',{name:'Read saved delivery settings'})).toBeVisible();await expect(d.getByRole('button',{name:'Submit recorded change'})).toBeDisabled();if(endpoint==='consume'){await expect(d.getByRole('status')).toContainText('did not verify');await expect(d.getByLabel('Verification proof')).toHaveValue('');}
});
for(const [value,heading]of [['forbidden','This view is not available to your account.'],['unavailable','The service is temporarily unavailable.'],['malformed','The response could not be displayed safely.'],['empty','No delivery targets returned.']])test(`delivery ${value} state`,async({page,context})=>{await context.addCookies([{name:'m5-delivery',value,url:origin}]);await page.goto(origin+'/settings/notifications');const section=page.locator('section').filter({has:page.getByRole('heading',{name:'Delivery targets',exact:true})});await expect(section.getByText(heading,{exact:true})).toBeVisible();});
test('ambiguous verification is locked without retry',async({page})=>{let calls=0;await page.route('**/api/notifications/verification/issue',r=>{calls++;return r.fulfill({status:503,contentType:'application/json',body:'{}'});});await page.goto(origin+'/settings/notifications');await page.getByRole('button',{name:'Request verification challenge',exact:true}).click();const d=page.getByRole('dialog',{name:'Request verification challenge',exact:true});await d.getByRole('button',{name:'Submit recorded change'}).click();await expect(d.getByRole('status')).toContainText('outcome is unconfirmed');await page.keyboard.press('Escape');await page.getByRole('button',{name:'Submit verification proof',exact:true}).click();const other=page.getByRole('dialog',{name:'Submit verification proof',exact:true});await expect(other.getByRole('button',{name:'Submit recorded change'})).toBeDisabled();expect(calls).toBe(1);});
for(const exit of ['timeout','unmount'])test(`delivery ${exit} aborts browser waiting without retry`,async({page})=>{
 await page.addInitScript(()=>{const original=fetch.bind(window),probe={calls:0,aborts:0,key:''};Object.assign(window,{deliveryProbe:probe});window.fetch=(input,init)=>{if(!String(input).endsWith('/api/notifications/verification/issue'))return original(input,init);probe.calls++;probe.key=new Headers(init?.headers).get('idempotency-key')??'';return new Promise<Response>((_,reject)=>{init?.signal?.addEventListener('abort',()=>{probe.aborts++;reject(new DOMException('Controlled abort','AbortError'));},{once:true});});};});
 const probe=()=>page.evaluate(()=>Reflect.get(window,'deliveryProbe') as {calls:number;aborts:number;key:string});await page.clock.install({time:new Date('2026-10-02T00:00:00Z')});await page.goto(origin+'/settings/notifications');await page.clock.pauseAt(new Date('2026-10-02T01:00:00Z'));await page.getByRole('button',{name:'Request verification challenge',exact:true}).click();const d=page.getByRole('dialog',{name:'Request verification challenge',exact:true});await d.getByRole('button',{name:'Submit recorded change'}).evaluate((b:HTMLButtonElement)=>{b.click();b.click();});await expect.poll(async()=>(await probe()).calls).toBe(1);expect((await probe()).key).toBeTruthy();if(exit==='timeout'){await page.clock.fastForward(30000);await expect(d.getByRole('status')).toContainText('outcome is unconfirmed');}else{await page.keyboard.press('Escape');await page.getByRole('link',{name:'Journal',exact:true}).click();}await expect.poll(async()=>(await probe()).aborts).toBe(1);await page.clock.fastForward(60000);expect((await probe()).calls).toBe(1);
});
