import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
const wrongCase=JSON.parse(readFileSync(new URL('../../../../contracts/backend/mocks/journal-cases-list.json',import.meta.url),'utf8')).data.cases[0];wrongCase.identity.caseId='another-owner-case';wrongCase.status='canceled';
const origin='http://127.0.0.1:3102';
for(const width of [390,768,1024,1440,1920])test(`journal analysis and influence preserve evidence at ${width}`,async({page},info)=>{
 await page.setViewportSize({width,height:1000});let writes=0;page.on('request',r=>{if(r.method()==='POST'&&r.url().includes('/api/journal/'))writes++;});
 await page.goto(origin+'/journal/analytics');await expect(page.getByRole('heading',{name:'Read the recorded history.'})).toBeVisible();await expect(page.getByText('Review the recorded entry timing.',{exact:true})).toBeVisible();await expect(page.getByText('No month supplied.',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath(`journal-analytics-${width}.png`),fullPage:true});
 await page.getByRole('link',{name:'Case influence',exact:true}).click();await expect(page.getByRole('heading',{name:'Understand case influence.'})).toBeVisible();await expect(page.getByText('Limited recorded history.',{exact:true})).toBeVisible();await expect(page.getByRole('table',{name:'Direction patterns'})).toContainText('Not available');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath(`journal-influence-${width}.png`),fullPage:true});expect(writes).toBe(0);expect(await page.locator('body').innerText()).not.toContain('private-subject');
});
test('empty, malformed, forbidden and unavailable journal snapshots stay distinct',async({page,context})=>{
 for(const [value,text] of [['empty','No case influence snapshot yet.'],['malformed','The response could not be displayed safely.'],['forbidden','This view is not available to your account.'],['unavailable','The service is temporarily unavailable.']]){
  await context.addCookies([{name:'m5-journal-analysis',value,url:origin}]);await page.goto(origin+'/journal/influence');await expect(page.getByRole('heading',{name:text})).toBeVisible();
 }
});
test('explicit influence generation sends one stable-key request and requires a full snapshot',async({page})=>{
 await page.goto(origin+'/journal/influence');await page.getByText('Generate case influence',{exact:true}).click();const requested=page.waitForRequest(r=>r.method()==='POST'&&r.url().endsWith('/api/journal/influence/generate'));await page.getByRole('button',{name:'Request case influence',exact:true}).click();const request=await requested;expect(request.headers()['idempotency-key']).toBeTruthy();expect(request.postData()).toBeNull();await expect(page.getByRole('status')).toContainText('A new snapshot was returned.');
});
const actions=[
 {status:'draft',action:'plan',label:'Record plan',fields:{}},
 {status:'planned',action:'execute',label:'Record execution',fields:{'Opened at · UTC':'2026-09-30T10:00'}},
 {status:'executed',action:'adjust',label:'Adjust record',fields:{}},
 {status:'executed',action:'partial-close',label:'Record partial closure',fields:{}},
 {status:'executed',action:'close',label:'Close case',fields:{'Closed at · UTC':'2026-09-30T12:00'}},
 {status:'planned',action:'cancel',label:'Cancel case',fields:{}},
 {status:'closed',action:'review',label:'Record review',fields:{'Reviewed at · UTC':'2026-09-30T14:00'}},
];
for(const action of actions)test(`case lifecycle ${action.action} has one authoritative record submission`,async({page,context})=>{
 await context.addCookies([{name:'m5-case-status',value:action.status,url:origin}]);await page.goto(origin+'/journal/jcase-demo-001');await page.getByRole('button',{name:action.label,exact:true}).click();const dialog=page.getByRole('dialog',{name:action.label,exact:true});for(const [label,value]of Object.entries(action.fields))await dialog.getByLabel(label,{exact:true}).fill(value!);
 if(action.action==='close')await dialog.getByLabel('Recorded outcome',{exact:true}).selectOption('loss');
 const requested=page.waitForRequest(r=>r.method()==='POST'&&r.url().endsWith('/'+action.action));await dialog.getByRole('button',{name:'Confirm recorded change'}).click();const request=await requested;expect(request.headers()['idempotency-key']).toBeTruthy();expect(request.postDataJSON()).not.toHaveProperty('subjectId');await expect(dialog.getByRole('status')).toContainText('The service returned the updated case.');await expect(dialog.getByRole('button',{name:'Confirm recorded change'})).toBeDisabled();await expect(dialog.getByRole('link',{name:'Read saved case ↗'})).toHaveAttribute('href','/journal/jcase-demo-001');
});
for(const width of [390,768,1024,1440,1920])test(`case dialogs and recorded replay keyboard at ${width}`,async({page},info)=>{
 await page.setViewportSize({width,height:1000});await page.goto(origin+'/journal/jcase-demo-001');const trigger=page.getByRole('button',{name:'Record execution',exact:true});await trigger.focus();await page.keyboard.press('Enter');const dialog=page.getByRole('dialog',{name:'Record execution',exact:true});await expect(dialog).toBeVisible();await dialog.getByRole('button',{name:'Close Record execution',exact:true}).focus();await page.keyboard.press('Shift+Tab');await expect(dialog.getByRole('button',{name:'Confirm recorded change'})).toBeFocused();await page.keyboard.press('Tab');await expect(dialog.getByRole('button',{name:'Close Record execution',exact:true})).toBeFocused();expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);await page.screenshot({path:info.outputPath(`journal-lifecycle-${width}.png`)});await page.keyboard.press('Escape');await expect(trigger).toBeFocused();await page.getByRole('button',{name:'View case history'}).click();const history=page.getByRole('dialog',{name:'Case history',exact:true});await expect(history).toContainText('Plan recorded for review.');expect(await history.innerText()).not.toContain('private-actor');expect(await page.content()).not.toContain('private-snapshot');await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'View case history'})).toBeFocused();
});
for(const response of ['conflict','unknown','wrong-case'])test(`case ${response} outcome locks all lifecycle submissions`,async({page})=>{
 let writes=0;await page.route('**/api/journal/cases/jcase-demo-001/cancel',route=>{writes++;return route.fulfill({status:response==='conflict'?409:response==='unknown'?503:200,contentType:'application/json',body:JSON.stringify(response==='wrong-case'?{ok:true,data:{case:wrongCase}}:{ok:false,error:{code:response==='conflict'?'conflict':'dependency_failed',message:'Controlled rejection'}})});});await page.goto(origin+'/journal/jcase-demo-001');await page.getByRole('button',{name:'Cancel case',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Cancel case',exact:true});await dialog.getByRole('button',{name:'Confirm recorded change'}).click();await expect(dialog.getByRole('status')).toContainText(response==='conflict'?'conflict':'unconfirmed');await page.keyboard.press('Escape');await page.getByRole('button',{name:'Record execution',exact:true}).click();await expect(page.getByRole('dialog',{name:'Record execution',exact:true}).getByRole('button',{name:'Confirm recorded change'})).toBeDisabled();expect(writes).toBe(1);
});
for(const exit of ['timeout','unmount'])test(`case ${exit} aborts browser wait without claiming server cancellation`,async({page})=>{
 await page.addInitScript(()=>{const original=fetch.bind(window);const probe={calls:0,aborts:0,key:''};Object.assign(window,{journalProbe:probe});window.fetch=(input,init)=>{if(!String(input).endsWith('/api/journal/cases/jcase-demo-001/cancel'))return original(input,init);probe.calls++;probe.key=new Headers(init?.headers).get('idempotency-key')??'';return new Promise<Response>((_,reject)=>{init?.signal?.addEventListener('abort',()=>{probe.aborts++;reject(new DOMException('Controlled abort','AbortError'));},{once:true});});};});
 const probe=()=>page.evaluate(()=>Reflect.get(window,'journalProbe') as {calls:number;aborts:number;key:string});await page.clock.install({time:new Date('2026-10-01T00:00:00Z')});await page.goto(origin+'/journal/jcase-demo-001');await page.clock.pauseAt(new Date('2026-10-01T01:00:00Z'));await page.getByRole('button',{name:'Cancel case',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Cancel case',exact:true});await dialog.getByRole('button',{name:'Confirm recorded change'}).evaluate((b:HTMLButtonElement)=>{b.click();b.click();});await expect.poll(async()=>(await probe()).calls).toBe(1);expect((await probe()).key).toBeTruthy();
 if(exit==='timeout'){await page.clock.fastForward(30000);await expect(dialog.getByRole('status')).toContainText('The service may still finish the operation.');}else{await page.keyboard.press('Escape');await page.getByRole('link',{name:'Journal',exact:true}).click();}
 await expect.poll(async()=>(await probe()).aborts).toBe(1);await page.clock.fastForward(60000);expect((await probe()).calls).toBe(1);expect((await probe()).aborts).toBe(1);
});
