import {test,expect} from '@playwright/test';
const origin='http://127.0.0.1:3102';
for(const width of [390,768,1024,1440,1920])test(`portfolio entity families and history at ${width}`,async({page},info)=>{
 await page.setViewportSize({width,height:1000});let writes=0;page.on('request',r=>{if(['POST','PATCH'].includes(r.method())&&r.url().includes('/api/portfolio/'))writes++;});
 for(const [path,title]of [['','Keep context beside the record.'],['/watchlist','A watchlist with a thesis.'],['/positions','Positions, as recorded.'],['/actions','Keep the next review in view.']]){await page.goto(origin+'/portfolio'+path);await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);if([390,1440].includes(width))await page.screenshot({path:info.outputPath(`portfolio-${path.slice(1)||'overview'}-${width}.png`),fullPage:true});}
 await page.goto(origin+'/portfolio/positions?selected=position-demo-001#record');await expect(page.locator('#record')).toContainText('Not recorded');await page.getByRole('button',{name:'View entity history'}).click();const history=page.getByRole('dialog',{name:'Entity history',exact:true});await expect(history).toContainText('Portfolio entity created.');expect(await page.content()).not.toContain('private-snapshot');expect(await page.content()).not.toContain('private-portfolio-subject');await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'View entity history'})).toBeFocused();expect(writes).toBe(0);
});
const cases=[
 {route:'watchlist',action:'watchlist',label:'Add watchlist entry',fields:{'Market identifier':'EUR/USD'},selects:{Timeframe:'H4',Priority:'high'}},
 {route:'watchlist?selected=watch-demo-001',action:'watch-demo-001',label:'Edit watchlist entry',fields:{'Recorded note · optional':'Controlled revised note'},selects:{}},
 {route:'watchlist?selected=watch-demo-001',action:'status',label:'Change watchlist status',fields:{},selects:{'Next recorded status':'readiness_pending'}},
 {route:'watchlist?selected=watch-demo-001',action:'thesis-health',label:'Record thesis health',fields:{},selects:{'Recorded thesis health':'weakening'}},
 {route:'watchlist?selected=watch-demo-001',action:'archive',label:'Archive entry',fields:{},selects:{}},
 {route:'positions',action:'positions',label:'Add proposed position',fields:{'Market identifier':'XAU/USD'},selects:{Timeframe:'H4','Recorded direction':'long'}},
 {route:'positions?selected=position-demo-001',action:'position-demo-001',label:'Edit position record',fields:{'Recorded size · optional':'0'},selects:{}},
 {route:'positions?selected=position-demo-001',action:'open',label:'Record position opening',fields:{'Opened at · UTC':'2026-09-30T10:00'},selects:{},scenario:'proposed'},
 {route:'positions?selected=position-demo-001',action:'reduce',label:'Record position reduction',fields:{'Recorded remaining size · optional':'0'},selects:{}},
 {route:'positions?selected=position-demo-001',action:'close',label:'Record position closure',fields:{'Closed at · UTC':'2026-09-30T12:00'},selects:{}},
 {route:'positions?selected=position-demo-001',action:'cancel',label:'Cancel proposed record',fields:{},selects:{},scenario:'proposed'},
 {route:'positions?selected=position-demo-001',action:'thesis-health',label:'Record thesis health',fields:{},selects:{'Recorded thesis health':'weakening'}},
 {route:'actions',action:'actions',label:'Add action item',fields:{'Action headline':'Review context','Recorded rationale':'Controlled recorded reasoning'},selects:{'Action kind':'review_thesis',Priority:'high'}},
 {route:'actions?selected=action-demo-001',action:'action-demo-001',label:'Edit action item',fields:{'Action headline · optional':'Revised recorded review'},selects:{}},
 {route:'actions?selected=action-demo-001',action:'complete',label:'Mark action completed',fields:{},selects:{}},
 {route:'actions?selected=action-demo-001',action:'dismiss',label:'Dismiss action',fields:{},selects:{}},
 {route:'',action:'generate',label:'Generate portfolio snapshot',fields:{},selects:{}},
];
for(const sample of cases)test(`portfolio ${sample.label} ${sample.route} is explicit and idempotent`,async({page,context})=>{
 if(sample.scenario)await context.addCookies([{name:'m5-portfolio',value:sample.scenario,url:origin}]);await page.goto(origin+'/portfolio/'+sample.route);await page.getByRole('button',{name:sample.label,exact:true}).click();const dialog=page.getByRole('dialog',{name:sample.label,exact:true});for(const [name,value]of Object.entries(sample.fields))await dialog.getByLabel(name,{exact:true}).fill(value!);for(const [name,value]of Object.entries(sample.selects))await dialog.getByLabel(name,{exact:true}).selectOption(value!);
 const awaited=page.waitForRequest(r=>['POST','PATCH'].includes(r.method())&&r.url().endsWith('/'+sample.action));await dialog.getByRole('button',{name:'Confirm recorded change'}).click();const req=await awaited;expect(req.headers()['idempotency-key']).toBeTruthy();if(req.postData())expect(req.postDataJSON()).not.toHaveProperty('subjectId');await expect(dialog.getByRole('status')).toContainText('The service returned the saved record.');await expect(dialog.getByRole('button',{name:'Confirm recorded change'})).toBeDisabled();if(sample.label==='Add proposed position'){await dialog.getByRole('link',{name:'Read saved record ↗'}).click();await expect(page).toHaveURL(/positions\?selected=position-created#record/);await expect(page.locator('#record')).toContainText('proposed');}
});
test('portfolio forbidden, unavailable, malformed and empty are distinct',async({page,context})=>{
 for(const [value,heading]of [['forbidden','This view is not available to your account.'],['unavailable','The service is temporarily unavailable.'],['malformed','The response could not be displayed safely.'],['empty','No portfolio watchlist entries returned.']]){await context.addCookies([{name:'m5-portfolio',value,url:origin}]);await page.goto(origin+'/portfolio/watchlist');await expect(page.getByRole('heading',{name:heading,exact:true})).toBeVisible();}
});
test('portfolio unknown outcome locks the entity dialogs without retry',async({page})=>{
 let count=0;await page.route('**/api/portfolio/watchlist/watch-demo-001/archive',route=>{count++;return route.fulfill({status:503,contentType:'application/json',body:'{}'});});await page.goto(origin+'/portfolio/watchlist?selected=watch-demo-001');await page.getByRole('button',{name:'Archive entry',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Archive entry',exact:true});await dialog.getByRole('button',{name:'Confirm recorded change'}).click();await expect(dialog.getByRole('status')).toContainText('The service may still finish');await page.keyboard.press('Escape');await page.getByRole('button',{name:'Edit watchlist entry',exact:true}).click();await expect(page.getByRole('dialog',{name:'Edit watchlist entry',exact:true}).getByRole('button',{name:'Confirm recorded change'})).toBeDisabled();expect(count).toBe(1);
});
for(const exit of ['timeout','unmount'])test(`portfolio ${exit} aborts only browser waiting`,async({page})=>{
 await page.addInitScript(()=>{const original=fetch.bind(window),probe={calls:0,aborts:0,key:''};Object.assign(window,{portfolioProbe:probe});window.fetch=(input,init)=>{if(!String(input).endsWith('/api/portfolio/watchlist/watch-demo-001/archive'))return original(input,init);probe.calls++;probe.key=new Headers(init?.headers).get('idempotency-key')??'';return new Promise<Response>((_,reject)=>{init?.signal?.addEventListener('abort',()=>{probe.aborts++;reject(new DOMException('Controlled abort','AbortError'));},{once:true});});};});
 const probe=()=>page.evaluate(()=>Reflect.get(window,'portfolioProbe') as {calls:number;aborts:number;key:string});await page.clock.install({time:new Date('2026-10-01T00:00:00Z')});await page.goto(origin+'/portfolio/watchlist?selected=watch-demo-001');await page.clock.pauseAt(new Date('2026-10-01T01:00:00Z'));await page.getByRole('button',{name:'Archive entry',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Archive entry',exact:true});await dialog.getByRole('button',{name:'Confirm recorded change'}).evaluate((b:HTMLButtonElement)=>{b.click();b.click();});await expect.poll(async()=>(await probe()).calls).toBe(1);expect((await probe()).key).toBeTruthy();if(exit==='timeout'){await page.clock.fastForward(30000);await expect(dialog.getByRole('status')).toContainText('The service may still finish');}else{await page.keyboard.press('Escape');await page.getByRole('link',{name:'Journal',exact:true}).click();}await expect.poll(async()=>(await probe()).aborts).toBe(1);await page.clock.fastForward(60000);expect((await probe()).calls).toBe(1);
});
test('portfolio form keyboard focus stays contained and restores at mobile width',async({page},info)=>{
 await page.setViewportSize({width:390,height:900});await page.goto(origin+'/portfolio/watchlist');const trigger=page.getByRole('button',{name:'Add watchlist entry',exact:true});await trigger.focus();await page.keyboard.press('Enter');const dialog=page.getByRole('dialog',{name:'Add watchlist entry',exact:true});await dialog.getByRole('button',{name:'Close Add watchlist entry',exact:true}).focus();await page.keyboard.press('Shift+Tab');await expect(dialog.getByRole('button',{name:'Confirm recorded change'})).toBeFocused();await page.keyboard.press('Tab');await expect(dialog.getByRole('button',{name:'Close Add watchlist entry',exact:true})).toBeFocused();expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);await page.screenshot({path:info.outputPath('portfolio-form-390.png')});await page.keyboard.press('Escape');await expect(trigger).toBeFocused();
});
