import {test,expect} from '@playwright/test';
const origin='http://127.0.0.1:3102';
for(const width of [390,768,1440])test(`account and freshness overlays at ${width}`,async({page},info)=>{
 await page.setViewportSize({width,height:900});const writes:string[]=[];page.on('request',r=>{if(r.method()==='POST')writes.push(r.url());});await page.goto(origin+'/workspace');await page.getByRole('button',{name:'Account',exact:true}).click();const a=page.getByRole('dialog',{name:'Your account',exact:true});await expect(a.getByRole('link',{name:'Read access and usage'})).toHaveAttribute('href','/settings/access');await expect(a.getByRole('link',{name:'Security and sign out'})).toHaveAttribute('href','/settings/security');await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Account',exact:true})).toBeFocused();
 await page.getByRole('button',{name:'Data freshness',exact:true}).click();const d=page.getByRole('dialog',{name:'Freshness and refresh',exact:true});await expect(d.getByRole('heading',{name:'Latest refresh',exact:true})).toBeVisible();await expect(d.getByText('No domain freshness records returned.',{exact:true})).toBeVisible();expect(writes).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath(`application-overlays-${width}.png`),fullPage:true});await d.getByRole('button',{name:'Request snapshot refresh',exact:true}).click();await expect(d.getByRole('status')).toContainText('partial success');await expect(d.getByRole('button',{name:'Request snapshot refresh',exact:true})).toBeDisabled();expect(writes.filter(u=>u.endsWith('/api/refresh/run'))).toHaveLength(1);
});
for(const [status,code,message]of [[401,'unauthorized','session needs attention'],[403,'forbidden','did not authorize'],[409,'conflict','reported a conflict'],[429,'bad_request','limiting requests'],[503,'dependency_failed','unconfirmed']] as const)test(`global refresh ${status} remains locked without retries`,async({page})=>{let calls=0;await page.route('**/api/refresh/run',r=>{calls++;return r.fulfill({status,contentType:'application/json',body:JSON.stringify({ok:false,error:{code,message:'Controlled failure'}})});});await page.goto(origin+'/workspace');await page.getByRole('button',{name:'Data freshness',exact:true}).click();const d=page.getByRole('dialog',{name:'Freshness and refresh',exact:true});await d.getByRole('button',{name:'Request snapshot refresh',exact:true}).click();await expect(d.getByRole('status')).toContainText(message);await expect(d.getByRole('button',{name:'Request snapshot refresh',exact:true})).toBeDisabled();expect(calls).toBe(1);});
for(const exit of ['timeout','close','unmount'])test(`global refresh ${exit} cleans waiting without claiming cancellation`,async({page})=>{
 await page.addInitScript(()=>{const original=fetch.bind(window),probe={calls:0,aborts:0};Object.assign(window,{globalRefreshProbe:probe});window.fetch=(input,init)=>{if(!String(input).endsWith('/api/refresh/run'))return original(input,init);probe.calls++;return new Promise<Response>((_,reject)=>{init?.signal?.addEventListener('abort',()=>{probe.aborts++;reject(new DOMException('Controlled abort','AbortError'));},{once:true});});};});await page.clock.install({time:new Date('2026-10-03T00:00:00Z')});await page.goto(origin+'/workspace');await page.clock.pauseAt(new Date('2026-10-03T01:00:00Z'));await page.getByRole('button',{name:'Data freshness',exact:true}).click();const d=page.getByRole('dialog',{name:'Freshness and refresh',exact:true});await d.getByRole('button',{name:'Request snapshot refresh',exact:true}).evaluate((b:HTMLButtonElement)=>{b.click();b.click();});
 if(exit==='timeout'){await page.clock.fastForward(30000);await expect(d.getByRole('status')).toContainText('unconfirmed');}else if(exit==='close')await page.keyboard.press('Escape');else await page.locator('nav[aria-label="Application navigation"] a[href="/journal"]').evaluate((a:HTMLAnchorElement)=>a.click());await expect.poll(()=>page.evaluate(()=>Reflect.get(window,'globalRefreshProbe'))).toEqual({calls:1,aborts:1});await page.clock.fastForward(60000);expect(await page.evaluate(()=>Reflect.get(window,'globalRefreshProbe'))).toEqual({calls:1,aborts:1});
});
test('unknown routes have an authored 404',async({page})=>{expect((await page.goto(origin+'/not-a-real-elceo-route'))?.status()).toBe(404);await expect(page.getByRole('heading',{name:'This page is unavailable.',exact:true})).toBeVisible();});
