import Link from 'next/link';
import {requireAuthenticatedSession} from '../../lib/auth/server';
import {readOwnedOperation} from '../../lib/api/owned-read';
import {OperationalChrome} from '../../components/app/OperationalChrome';
import {ReadState} from '../../components/app/ReadState';
import {AccountPreferenceForm} from '../settings/AccountPreferenceForm';
import {accountPreferences} from '../settings/account-projection';
import {SettingsNav} from '../settings/SettingsNav';
import {envelope} from '../workspace/projection';
import {targetProjection,subscriptionProjection,healthProjection,receiptProjection,projectList} from './settings-projection';
import {DeliveryMutation} from './DeliveryMutation';
import styles from './DeliverySettings.module.css';
import ui from '../../components/app/Operational.module.css';
export async function DeliverySettingsPage(){
 const session=await requireAuthenticatedSession('/settings/notifications');
 const [tr,sr,hr,ar]=await Promise.all([readOwnedOperation('GET /api/notifications/targets',{idempotency:{key:crypto.randomUUID()}}),readOwnedOperation('GET /api/notifications/subscriptions',{idempotency:{key:crypto.randomUUID()}}),readOwnedOperation('GET /api/notifications/health',{}),readOwnedOperation('GET /api/account/state',{})]);
 const targets=tr.kind==='success'?projectList(envelope(tr.value)?.targets,targetProjection):null,subscriptions=sr.kind==='success'?projectList(envelope(sr.value)?.subscriptions,subscriptionProjection):null;
 const health=hr.kind==='success'?projectList(envelope(hr.value)?.degradedTargets,healthProjection):null,receipts=hr.kind==='success'?projectList(envelope(hr.value)?.criticalReceipts,receiptProjection):null;
 const preferences=ar.kind==='success'?accountPreferences(envelope(ar.value)):null;
 return <OperationalChrome session={session}><header className={ui.title}><div><h1>Choose where context reaches you.</h1><p>Targets, verification and subscriptions are distinct from delivery health. This is your configuration; <Link href="/notifications">open the inbox</Link> for received information.</p></div></header><SettingsNav/><div className={styles.sections}><section><header className={styles.heading}><h2>Account preferences</h2><p>Choose notification channels and alert classes separately from delivery infrastructure.</p></header>{ar.kind!=='success'?<ReadState kind={ar.kind}/>:preferences?<AccountPreferenceForm mode="notifications" preferences={preferences}/>:<ReadState kind="invalid_payload"/>}</section>
 <section><header className={styles.heading}><h2>Delivery targets</h2><p>A configured destination is not proof of verification or successful delivery.</p></header>{tr.kind!=='success'?<ReadState kind={tr.kind}/>:!targets?<ReadState kind="invalid_payload"/>:<><DeliveryMutation offers={['target-create']}/>{!targets.length?<p>No delivery targets returned.</p>:<ul className={styles.records}>{targets.map(t=><li key={t.targetId}><div><h3>{t.label??t.channel.replaceAll('_',' ')}</h3><p>{t.destination??(t.channel==='in_app'?'Your in-app destination':'Destination details unavailable in this view.')}</p><p>{t.targetId}</p></div><div><dl className={styles.facts}><div><dt>Channel</dt><dd>{t.channel}</dd></div><div><dt>Recorded status</dt><dd>{t.status}</dd></div><div><dt>Verification recorded</dt><dd>{t.verifiedAt??'Not recorded'}</dd></div><div><dt>Updated</dt><dd>{t.updatedAt}</dd></div></dl><DeliveryMutation id={t.targetId} channel={t.channel} offers={[...(t.status==='active'?['target-disable' as const]:t.targetKind==='in_app_user'||t.verifiedAt?['target-enable' as const]:[]),...(t.targetKind!=='in_app_user'&&!t.verifiedAt?['verification-issue' as const,'verification-consume' as const]:[])]}/></div></li>)}</ul>}</> }</section>
 <section><header className={styles.heading}><h2>Channel subscriptions</h2><p>Enabled state and minimum materiality are recorded by the service. They do not grant entitlement.</p></header>{sr.kind!=='success'?<ReadState kind={sr.kind}/>:!subscriptions?<ReadState kind="invalid_payload"/>:<><DeliveryMutation offers={['subscription-create']}/>{!subscriptions.length?<p>No channel subscriptions returned.</p>:<ul className={styles.records}>{subscriptions.map(s=><li key={s.subscriptionId}><div><h3>{s.channel.replaceAll('_',' ')}</h3><p>{s.subscriptionId}</p></div><div><dl className={styles.facts}><div><dt>Subscription</dt><dd>{s.enabled?'Enabled':'Disabled'}</dd></div><div><dt>Minimum materiality</dt><dd>{s.minMaterialityScore??'No threshold recorded'}</dd></div><div><dt>Market / timeframe</dt><dd>{s.asset} / {s.timeframe}</dd></div><div><dt>Rule scope</dt><dd>{s.ruleKey}</dd></div><div><dt>Updated</dt><dd>{s.updatedAt}</dd></div></dl><DeliveryMutation offers={['subscription-update']} id={s.subscriptionId} channel={s.channel}/></div></li>)}</ul>}</>}<p className={styles.notice}>The current subscription handler does not persist minimum priority or decision-kind filters. These controls are unavailable rather than shown as saved.</p></section>
 <section><header className={styles.heading}><h2>Delivery health</h2><p>Owner-scoped degraded targets and recent critical receipts. An empty result does not certify provider health.</p></header>{hr.kind!=='success'?<ReadState kind={hr.kind}/>:!health||!receipts?<ReadState kind="invalid_payload"/>:<><h3>Degraded targets</h3>{!health.length?<p>No degraded target records returned.</p>:<ul className={styles.records}>{health.map(h=><li key={h.targetId}><h3>{h.targetId}</h3><dl className={styles.facts}><div><dt>Health</dt><dd>{h.healthState}</dd></div><div><dt>Last receipt</dt><dd>{h.lastReceiptKind??'Not recorded'}</dd></div><div><dt>Recorded</dt><dd>{h.lastReceiptAt??'Not recorded'}</dd></div></dl></li>)}</ul>}<h3>Critical receipts</h3>{!receipts.length?<p>No critical receipts returned.</p>:<ul className={styles.records}>{receipts.map(r=><li key={r.receiptId}><h3>{r.eventKind.replaceAll('_',' ')}</h3><dl className={styles.facts}><div><dt>Provider / channel</dt><dd>{r.providerKind} / {r.channel}</dd></div><div><dt>Occurred</dt><dd>{r.occurredAt}</dd></div><div><dt>Target</dt><dd>{r.targetId??'Not recorded'}</dd></div><div><dt>Reason code</dt><dd>{r.reasonCode??'Not supplied'}</dd></div></dl></li>)}</ul>}</>}</section></div></OperationalChrome>;
}
