import Link from 'next/link';
import {requireAuthenticatedSession} from '../../lib/auth/server';
import {readOwnedOperation} from '../../lib/api/owned-read';
import {OperationalChrome} from '../../components/app/OperationalChrome';
import {ReadState} from '../../components/app/ReadState';
import {envelope} from '../workspace/projection';
import {inboxProjection,notificationSummary} from './projection';
import styles from '../../components/app/Operational.module.css';
const managementLabels=[['subjectTargetCount','Configured destinations'],['activeTargetCount','Active destinations'],['subscriptionCount','Subscriptions'],['enabledSubscriptionCount','Enabled subscriptions'],['inboxArchivedCount','Archived notifications'],['recentDeliveredCount','Recent deliveries'],['recentFailedCount','Recent failures'],['recentDeadCount','Recent dead deliveries']] as const;
const feedbackLabels=[['acceptedCount','Accepted'],['deliveredCount','Delivered'],['bouncedCount','Bounced'],['complainedCount','Complaints'],['unsubscribedCount','Unsubscribed'],['invalidTargetCount','Invalid destinations'],['providerFailedCount','Provider failures'],['unknownCount','Unknown outcomes'],['disabledTargetCount','Disabled destinations'],['degradedTargetCount','Degraded destinations']] as const;
export async function NotificationsPage({limit}:{limit:50|100|200}) {
 const session=await requireAuthenticatedSession('/notifications');
 const [inboxResult,summaryResult]=await Promise.all([readOwnedOperation('GET /api/notifications/inbox',{query:{limit}}),readOwnedOperation('GET /api/notifications/summary',{})]);
 const items=inboxResult.kind==='success'?inboxProjection(envelope(inboxResult.value)?.inbox):null;
 const summary=summaryResult.kind==='success'?notificationSummary(envelope(summaryResult.value)):null;
 return <OperationalChrome session={session}><header className={styles.title}><div><h1>Keep the context in view.</h1><p>Your notification record. Opening an item here does not mark it read, archive it or initiate delivery.</p></div></header><div className={styles.split}><section className={styles.panel}><h2>Inbox</h2>{inboxResult.kind!=='success'?<ReadState kind={inboxResult.kind}/>:!items?<ReadState kind="invalid_payload"/>:items.length===0?<section className={styles.state}><h3>Your inbox is clear.</h3><p>No notifications were returned for your account.</p></section>:<><ol className={styles.timeline}>{items.map(item=><li key={item.inboxId}><p className={styles.meta}><span>{item.asset} · {item.timeframe}</span><span>{item.readAt?'Read':'Unread'}{item.archivedAt?' · Archived':''}</span></p><details className={styles.details}><summary>{item.headline}</summary><p>{item.body}</p><dl className={styles.identityFields}><div><dt>Recorded</dt><dd><time dateTime={item.createdAt}>{item.createdAt}</time></dd></div>{item.readAt&&<div><dt>Read</dt><dd><time dateTime={item.readAt}>{item.readAt}</time></dd></div>}{item.archivedAt&&<div><dt>Archived</dt><dd><time dateTime={item.archivedAt}>{item.archivedAt}</time></dd></div>}</dl></details></li>)}</ol><p>{items.length<limit?'End of the currently available list.':limit===200?'Showing the maximum 200 returned items. Older records cannot be paged through here.':`Showing up to ${limit} notifications.`}</p>{items.length>=limit&&limit<200&&<Link className={styles.button} href={`/notifications?limit=${limit===50?100:200}`}>Read a larger window</Link>}</>}</section><aside><section className={styles.panel}><h2>Delivery context</h2>{summaryResult.kind!=='success'?<ReadState kind={summaryResult.kind}/>:!summary?<ReadState kind="invalid_payload"/>:<><dl className={styles.metrics}><div><dt>Unread, across your inbox</dt><dd>{summary.unread}</dd></div><div><dt>Degraded destinations</dt><dd>{String(summary.feedback.degradedTargetCount)}</dd></div></dl><p>Configured, verified and delivered are separate states. Delivery counts do not confirm that every destination is working.</p><details className={styles.details}><summary>Destination & subscription summary</summary><dl className={styles.identityFields}>{managementLabels.map(([key,label])=><div key={key}><dt>{label}</dt><dd>{String(summary.management[key])}</dd></div>)}</dl></details><details className={styles.details}><summary>Provider feedback</summary><dl className={styles.identityFields}>{feedbackLabels.map(([key,label])=><div key={key}><dt>{label}</dt><dd>{String(summary.feedback[key])}</dd></div>)}</dl></details></>}</section></aside></div></OperationalChrome>;
}
