// Display whitelist from frozen notifications.ts; never serialize raw addresses, ownership or provider payloads.
import {record} from '../workspace/projection.ts';
export const channels=['in_app','email','push','sms','webhook'] as const;
export type Channel=typeof channels[number];
const text=(v:unknown):v is string=>typeof v==='string';
const nullable=(v:unknown):v is string|null=>v===null||text(v);
export function targetProjection(value:unknown){const r=record(value);if(!r||!text(r.targetId)||!channels.includes(r.channel as Channel)||!['active','disabled','unverified'].includes(String(r.status))||!['in_app_user','email_address','push_endpoint'].includes(String(r.targetKind))||!nullable(r.label)||!nullable(r.verifiedAt)||!text(r.updatedAt))return null;
 let destination:string|null=null;try{const a=record(JSON.parse(String(r.addressJson)));if(r.channel==='email'&&text(a?.email))destination=a.email;}catch{/* Address remains unavailable; never render raw JSON. */}
 return {targetId:r.targetId,channel:r.channel as Channel,status:r.status as string,targetKind:r.targetKind as string,label:r.label,verifiedAt:r.verifiedAt,updatedAt:r.updatedAt,destination};}
export function subscriptionProjection(value:unknown){const r=record(value);if(!r||!['subscriptionId','asset','timeframe','ruleKey','updatedAt'].every(k=>text(r[k]))||!channels.includes(r.channel as Channel)||typeof r.enabled!=='boolean'||!(r.minMaterialityScore===null||typeof r.minMaterialityScore==='number'&&Number.isFinite(r.minMaterialityScore)))return null;return {subscriptionId:r.subscriptionId as string,channel:r.channel as Channel,asset:r.asset as string,timeframe:r.timeframe as string,ruleKey:r.ruleKey as string,enabled:r.enabled,minMaterialityScore:r.minMaterialityScore as number|null,updatedAt:r.updatedAt as string};}
export function projectList<T>(value:unknown,project:(v:unknown)=>T|null):T[]|null {if(!Array.isArray(value))return null;const result:T[]=[];for(const item of value){const v=project(item);if(!v)return null;result.push(v);}return result;}
export function healthProjection(value:unknown){const r=record(value);if(!r||!text(r.targetId)||!['healthy','warning','degraded','disabled'].includes(String(r.healthState))||!nullable(r.lastReceiptKind)||!nullable(r.lastReceiptAt)||!text(r.updatedAt))return null;return {targetId:r.targetId,healthState:r.healthState as string,lastReceiptKind:r.lastReceiptKind,lastReceiptAt:r.lastReceiptAt,updatedAt:r.updatedAt};}
export function receiptProjection(value:unknown){const r=record(value);if(!r||!['receiptId','providerKind','channel','eventKind','severity','occurredAt'].every(k=>text(r[k]))||!nullable(r.targetId)||!nullable(r.reasonCode))return null;return {receiptId:r.receiptId as string,providerKind:r.providerKind as string,channel:r.channel as string,eventKind:r.eventKind as string,severity:r.severity as string,occurredAt:r.occurredAt as string,targetId:r.targetId,reasonCode:r.reasonCode};}
export function verificationIssued(value:unknown,id:string){const r=record(value);return !!r&&r.targetId===id&&['verificationId','issuedAt','expiresAt'].every(k=>text(r[k]))&&['email_verification','push_verification'].includes(String(r.verificationKind))&&typeof r.alreadyActive==='boolean';}
export function verificationConsumed(value:unknown,id:string){const r=record(value);return !!r&&r.targetId===id&&text(r.verificationId)&&typeof r.verified==='boolean'&&nullable(r.reason)?{verified:r.verified,reason:r.reason}:null;}
