import Link from 'next/link';
import {requireAuthenticatedSession} from '../../lib/auth/server';
import {readOwnedOperation} from '../../lib/api/owned-read';
import {OperationalChrome} from '../../components/app/OperationalChrome';
import {ReadState} from '../../components/app/ReadState';
import {envelope} from '../workspace/projection';
import {journalAnalyticsProjection,journalInfluenceProjection} from './analysis-projection';
import {JournalNav} from './JournalNav';
import {GenerateInfluence} from './GenerateInfluence';
import ui from '../../components/app/Operational.module.css';
import styles from './JournalAnalysis.module.css';
type Row=Record<string,unknown>;
function Table({title,rows,columns}:{title:string;rows:Row[];columns:readonly(readonly[string,string])[]}){return rows.length?<table className={styles.table}><caption>{title}</caption><thead><tr>{columns.map(([key,label])=><th key={key} scope="col">{label}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{columns.map(([key,label])=><td key={key} data-label={label}>{r[key]===null?'Not available':String(r[key])}</td>)}</tr>)}</tbody></table>:<p>No {title.toLowerCase()} returned.</p>;}
function Notes({title,items}:{title:string;items:string[]}){return <section className={styles.section}><h2>{title}</h2>{items.length?<ul>{items.map((v,i)=><li key={i}>{v}</li>)}</ul>:<p>None returned by the service.</p>}</section>;}
function Metrics({values}:{values:readonly(readonly[string,unknown])[]}){return <dl className={styles.metrics}>{values.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value===null?'Not available':String(value)}</dd></div>)}</dl>;}
export async function JournalAnalysisPage({mode}:{mode:'analytics'|'influence'}){
 const session=await requireAuthenticatedSession(`/journal/${mode}`);
 const result=mode==='analytics'?await readOwnedOperation('GET /api/journal/analytics',{}):await readOwnedOperation('GET /api/journal/influence/latest',{});
 let content;
 if(result.kind!=='success')content=<ReadState kind={result.kind}/>;
 else if(mode==='analytics'){
  // Legacy analytics is dedicated JSON, not the standard data envelope.
  const v=journalAnalyticsProjection(result.value);
  content=!v?<ReadState kind="invalid_payload"/>:<>
   {v.totals.totalTrades===0&&<section className={ui.state}><h2>No journal-entry history to analyse yet.</h2><p>This report reads legacy journal entries. Canonical case records are a separate source for case influence.</p></section>}
   <div className={styles.lead}><section className={styles.diagnosis}><h2>{v.diagnosis}</h2><p>Service-reported confidence: {v.confidence}. Historical records do not guarantee future outcomes.</p></section><Metrics values={[[ 'Recorded trades',v.totals.totalTrades],['Win rate (%)',v.totals.winRate],['Expectancy (R)',v.totals.expectancy],['Average gain',v.totals.averageGain],['Average loss',v.totals.averageLoss],['Average risk/reward',v.totals.averageRiskReward]]}/></div>
   <section className={styles.section}><h2>Historical comparisons</h2><p>Order and values come from the service. P&L amounts have no currency supplied in this report; none is inferred.</p><div className={styles.columns}>{[['Best recorded month',v.bestMonth],['Worst recorded month',v.worstMonth]].map(([title,month])=><section key={String(title)}><h3>{String(title)}</h3>{month?<Table title="Monthly record" rows={[month as Row]} columns={[[ 'month','Month'],['tradeCount','Trades'],['netPnl','Net P&L'],['winRate','Win rate (%)']]}/>:<p>No month supplied.</p>}</section>)}</div><div className={styles.columns}><Table title="Best traded assets" rows={v.bestAssets} columns={[[ 'asset','Asset'],['tradeCount','Trades'],['netPnl','Net P&L'],['winRate','Win rate (%)']]}/><Table title="Worst traded assets" rows={v.worstAssets} columns={[[ 'asset','Asset'],['tradeCount','Trades'],['netPnl','Net P&L'],['winRate','Win rate (%)']]}/></div><Table title="Trading windows" rows={v.windows} columns={[[ 'session','Session'],['tradeCount','Trades'],['netPnl','Net P&L'],['expectancy','Expectancy (R)']]}/></section>
   <section className={styles.section}><h2>Recorded extremes</h2><div className={styles.columns}><Table title="Highest gains" rows={v.gains} columns={[[ 'asset','Asset'],['direction','Direction'],['pnlAmount','Recorded P&L'],['resultRMultiple','R multiple'],['closedAtUtc','Closed (UTC)']]}/><Table title="Highest losses" rows={v.losses} columns={[[ 'asset','Asset'],['direction','Direction'],['pnlAmount','Recorded P&L'],['resultRMultiple','R multiple'],['closedAtUtc','Closed (UTC)']]}/></div></section>
   <section className={styles.section}><h2>Behaviour & evidence</h2><p>Reported bias-violation rate: {v.biasViolationRate}</p><Table title="Repeated mistake categories" rows={v.mistakes} columns={[[ 'category','Category'],['count','Count']]}/><Table title="Poor time windows" rows={v.poorWindows} columns={[[ 'session','Session'],['tradeCount','Trades'],['netPnl','Net P&L'],['expectancy','Expectancy (R)']]}/><Table title="Evidence" rows={v.evidence} columns={[[ 'metric','Metric'],['value','Recorded value'],['interpretation','Interpretation']]}/></section>
   <div className={styles.columns}><Notes title="Overtrading observations" items={v.signals}/><Notes title="Confidence mismatches" items={v.mismatches}/></div><section className={styles.section}><h2>Service-proposed interventions</h2><Table title="Interventions" rows={v.interventions} columns={[[ 'action','Action'],['targetMetric','Target metric'],['successCriteria','Success criteria']]}/><Notes title="Monitoring plan" items={v.monitoring}/></section>
  </>;
 }else{
  const raw=envelope(result.value)?.snapshot,v=journalInfluenceProjection(raw);
  content=raw===null?<section className={ui.state}><h2>No case influence snapshot yet.</h2><p>Reading this page never generates one. Request generation explicitly when you want the service to review your case history.</p></section>:!v?<ReadState kind="invalid_payload"/>:<>
   <div className={styles.lead}><section className={styles.diagnosis}><h2>Patterns grounded in your case record.</h2><p>Scope: {String(v.context.asset)} · {String(v.context.timeframe)}. Generated <time dateTime={String(v.context.generatedAt)}>{String(v.context.generatedAt)}</time>.</p><p>Influence, associations and averages are server-owned observations, not forecasts or trading instructions.</p></section><Metrics values={[[ 'Reviewed cases',v.context.reviewedCaseCount],['Closed cases',v.context.closedCaseCount],['Recent cases',v.context.recentCaseCount]]}/></div>
   <div className={styles.columns}><Notes title="Cautions" items={v.cautions}/><Notes title="Confidence context" items={v.confidence}/></div>
   <section className={styles.section}><h2>Setup evidence</h2><Table title="Setup patterns" rows={v.setups} columns={[[ 'setupType','Setup'],['sampleCount','Sample'],['winCount','Wins'],['lossCount','Losses'],['breakevenCount','Breakeven'],['mixedCount','Mixed'],['avgRMultiple','Average R'],['avgPnlPercent','Average P&L (%)'],['influenceScore','Influence score']]}/>{v.setups.map((s,i)=><details className={ui.details} key={i}><summary>{String(s.setupType)} · execution quality</summary><dl className={ui.identityFields}>{Object.entries(s.quality).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></details>)}</section>
   <section className={styles.section}><h2>Behaviour associations</h2><Table title="Behaviour patterns" rows={v.behaviors} columns={[[ 'behaviorTag','Behaviour'],['sampleCount','Sample'],['negativeAssociationScore','Negative association'],['positiveAssociationScore','Positive association'],['influenceScore','Influence score']]}/></section>
   <section className={styles.section}><h2>Directional history</h2><p>Win ratio is returned on a 0–1 scale. Missing averages remain unavailable.</p><Table title="Direction patterns" rows={v.directions} columns={[[ 'direction','Direction'],['sampleCount','Sample'],['avgRMultiple','Average R'],['avgPnlPercent','Average P&L (%)'],['winRate','Win ratio (0–1)'],['influenceScore','Influence score']]}/></section>
   <div className={styles.columns}><Notes title="Repeated mistakes" items={v.mistakes}/><Notes title="Repeated strengths" items={v.strengths}/></div><section className={styles.section}><h2>Supporting case records</h2>{v.caseIds.length?<div className={styles.links}>{v.caseIds.map(id=><Link key={id} href={`/journal/${encodeURIComponent(id)}`}>{id} ↗</Link>)}</div>:<p>No supporting cases returned.</p>}</section>
  </>;
 }
 return <OperationalChrome session={session}><header className={ui.title}><div><h1>{mode==='analytics'?'Read the recorded history.':'Understand case influence.'}</h1><p>{mode==='analytics'?'A service-produced analysis of legacy journal entries, distinct from canonical case influence.':'A service-produced review of canonical journal cases, kept separate from entry analytics.'}</p></div></header><JournalNav/>{content}{mode==='influence'&&<GenerateInfluence/>}</OperationalChrome>;
}
