import Link from 'next/link';
import {requireAuthenticatedSession} from '../../lib/auth/server';
import {readOwnedOperation} from '../../lib/api/owned-read';
import {OperationalChrome} from '../../components/app/OperationalChrome';
import {ReadState} from '../../components/app/ReadState';
import {envelope} from '../workspace/projection';
import {journalCaseProjection} from './projection';
import styles from '../../components/app/Operational.module.css';
function Fields({record,labels}:{record:Record<string,unknown>;labels:readonly(readonly[string,string])[]}){return <dl className={styles.identityFields}>{labels.map(([key,label])=><div key={key}><dt>{label}</dt><dd>{record[key]===null?'Not recorded':Array.isArray(record[key])?(record[key] as number[]).join(' · ')||'None recorded':String(record[key])}</dd></div>)}</dl>;}
function Notes({title,items}:{title:string;items:string[]}){return <section className={styles.panel}><h2>{title}</h2>{items.length?<ul>{items.map((s,i)=><li key={i}>{s}</li>)}</ul>:<p>None recorded.</p>}</section>;}
export async function JournalPage({caseId}:{caseId?:string}){
 const session=await requireAuthenticatedSession(caseId?`/journal/${encodeURIComponent(caseId)}`:'/journal');
 const result=caseId?await readOwnedOperation('GET /api/journal/cases/{caseId}',{path:{caseId}}):await readOwnedOperation('GET /api/journal/cases',{idempotency:{key:crypto.randomUUID()}});
 let content;
 if(result.kind!=='success')content=<ReadState kind={result.kind}/>;
 else if(caseId){const v=journalCaseProjection(envelope(result.value)?.case);content=!v?<ReadState kind="invalid_payload"/>:<><header className={styles.title}><div><p>{v.asset} · {v.timeframe} · {v.status.replaceAll('_',' ')}</p><h1>{v.title}</h1><p>Created {v.createdAt} · Updated {v.updatedAt}</p></div></header><div className={styles.split}><section><section className={styles.panel}><h2>The recorded plan</h2><p>{String(v.plan.thesis)||'No thesis recorded.'}</p><Fields record={v.plan} labels={[[ 'direction','Direction'],['setupType','Setup'],['conviction','Conviction'],['entryPricePlanned','Planned entry'],['stopLossPlanned','Planned stop'],['takeProfitPlanned','Planned targets'],['riskAmountPlanned','Planned risk amount'],['riskPercentPlanned','Planned risk percent'],['invalidationNote','Invalidation note']]}/></section><Notes title="Execution checklist" items={v.checklist}/><section className={styles.panel}><h2>Execution record</h2><Fields record={v.execution} labels={[[ 'entryPriceExecuted','Recorded entry'],['positionSize','Position size'],['openedAt','Opened at'],['lastAdjustedAt','Last adjusted'],['executionQuality','Execution quality']]}/></section><Notes title="Execution notes" items={v.notes}/></section><aside><section className={styles.panel}><h2>Closure record</h2><Fields record={v.closure} labels={[[ 'outcome','Outcome'],['exitPrice','Exit price'],['closedAt','Closed at'],['pnlAmount','Recorded P&L amount'],['pnlPercent','Recorded P&L percent'],['rMultiple','Recorded R multiple'],['closureReason','Reason']]}/><p>These are recorded values, not a calculation or an execution instruction.</p></section><Notes title="What went well" items={v.wentWell}/><Notes title="What needs review" items={v.wentWrong}/><Notes title="Lessons" items={v.lessons}/><Notes title="Follow-up actions" items={v.followUp}/><Notes title="Behaviour tags" items={v.behaviorTags}/></aside></div></>;}
 else {const raw=envelope(result.value)?.cases,items=Array.isArray(raw)?raw.map(journalCaseProjection):null;content=!items||items.some(v=>!v)?<ReadState kind="invalid_payload"/>:!items.length?<section className={styles.state}><h2>Your case record begins here.</h2><p>No journal cases have been recorded. Start with a draft of your context and reasoning.</p></section>:<><ol className={styles.timeline}>{items.map(v=>v&&<li key={v.caseId}><p className={styles.meta}><span>{v.asset} · {v.timeframe}</span><span>{v.status.replaceAll('_',' ')}</span></p><h2><Link href={`/journal/${encodeURIComponent(v.caseId)}`}>{v.title} ↗</Link></h2><p>{String(v.plan.thesis)}</p><time dateTime={v.updatedAt}>{v.updatedAt}</time></li>)}</ol><p>{items.length<50?'End of the currently returned case list.':'Showing the most recent 50 returned cases.'}</p></>;}
 return <OperationalChrome session={session}>{!caseId&&<header className={styles.title}><div><h1>Keep the reasoning.</h1><p>A record of context, decisions and review. ELCEO records your activity; it does not place trades.</p></div><Link className={styles.button} href="/journal/new">Start a case ↗</Link></header>}<nav className={styles.tabs} aria-label="Journal"><Link href="/journal">Case record</Link><Link href="/journal/new">New draft</Link></nav>{content}</OperationalChrome>;
}
