import Link from 'next/link';
import {requireAuthenticatedSession} from '../../lib/auth/server';
import {readOwnedOperation} from '../../lib/api/owned-read';
import {OperationalChrome} from '../../components/app/OperationalChrome';
import {ReadState} from '../../components/app/ReadState';
import {envelope} from '../workspace/projection';
import {billingProjection,intentionProjection,entitlementProjection,usageProjection,accessDecisionsProjection} from './commercial-projection';
import {SettingsNav} from './SettingsNav';
import {BillingPortal} from './BillingPortal';
import styles from '../../components/app/Operational.module.css';
function Fields({value,labels}:{value:Record<string,unknown>;labels:readonly(readonly[string,string])[]}){return <dl className={styles.identityFields}>{labels.map(([key,label])=><div key={key}><dt>{label}</dt><dd>{value[key]===null?'Not recorded':typeof value[key]==='boolean'?(value[key]?'Yes':'No'):String(value[key]).replaceAll('_',' ')}</dd></div>)}</dl>;}
async function Billing(){
 const [billing,intention]=await Promise.all([readOwnedOperation('GET /api/account/billing',{}),readOwnedOperation('GET /api/billing/intention',{})]);
 const b=billing.kind==='success'?billingProjection(envelope(billing.value)?.snapshot):null,i=intention.kind==='success'?intentionProjection(intention.value):null;
 return <div className={styles.split}><section><section className={styles.panel}><h2>Recorded plan & subscription</h2>{billing.kind!=='success'?<ReadState kind={billing.kind}/>:!b?<ReadState kind="invalid_payload"/>:<><p className={styles.meta}>Recorded at <time dateTime={b.generatedAt}>{b.generatedAt}</time></p><Fields value={b.plan} labels={[[ 'kind','Plan'],['accountState','Account state'],['startedAt','Plan started'],['endsAt','Plan ends'],['trialEndsAt','Plan trial ends']]}/>{b.subscription?<Fields value={b.subscription} labels={[[ 'state','Subscription state'],['currentPeriodStart','Current period starts'],['currentPeriodEnd','Current period ends'],['trialEndsAt','Subscription trial ends'],['canceledAt','Cancellation recorded'],['willCancelAtPeriodEnd','Will cancel at period end']]}/>:<p>No subscription is recorded.</p>}</>}</section><section className={styles.panel}><h2>Existing payment intention</h2>{intention.kind!=='success'?<ReadState kind={intention.kind}/>:!i?<ReadState kind="invalid_payload"/>:i.kind==='none'?<p>No payment intention is recorded. This does not confirm provider readiness or a published price.</p>:<><Fields value={i} labels={[[ 'paymentState','Payment state'],['subscriptionState','Related subscription state'],['commercialAccessActive','Commercial access reported active'],['reconciliationRequired','Reconciliation required'],['newIntentionAllowed','New intention allowed'],['billingManagementRequired','Billing management required']]}/><p>{i.paymentState==='succeeded'?'Payment is recorded as succeeded. Product access still follows the separate entitlement decision.':i.paymentState==='unknown'||i.paymentState==='reconciliation_required'?'The outcome needs reconciliation. Do not start another payment to resolve this uncertainty.':i.paymentState==='failed'?'This payment is recorded as failed. Read the canonical state before considering another intention.':i.paymentState==='processing'||i.paymentState==='pending_provider'?'The recorded payment is still in progress. A browser return is not a completion signal.':'This is the payment state currently recorded by the service.'}</p>{i.checkoutUrl&&<a className={styles.button} href={i.checkoutUrl} rel="noreferrer">Continue existing checkout at {new URL(i.checkoutUrl).hostname} ↗</a>}</>}</section></section><aside><BillingPortal/><section className={styles.state}><h2>New checkout is not available here yet.</h2><p>A published price and supported provider/currency selection are needed before a new checkout can be offered. This screen will not guess those details or initiate a payment.</p><Link href="/pricing">Read plan information ↗</Link></section></aside></div>;
}
async function Access(){
 const [profile,usage,decisions]=await Promise.all([readOwnedOperation('GET /api/account/entitlements',{}),readOwnedOperation('GET /api/account/usage',{}),readOwnedOperation('GET /api/account/access-decisions',{})]);
 const p=profile.kind==='success'?entitlementProjection(envelope(profile.value)):null,u=usage.kind==='success'?usageProjection(envelope(usage.value)?.usage):null,d=decisions.kind==='success'?accessDecisionsProjection(envelope(decisions.value)?.decisions):null;
 return <><div className={styles.split}><section className={styles.panel}><h2>Current access profile</h2>{profile.kind!=='success'?<ReadState kind={profile.kind}/>:!p?<ReadState kind="invalid_payload"/>:<><p>{p.plan} · {p.state}</p><p className={styles.meta}>Recorded at {p.generatedAt}</p>{[['Allowed',p.allowed],['Blocked',p.blocked]] .map(([label,items])=><section key={String(label)}><h3>{String(label)}</h3>{(items as string[]).length?<ul>{(items as string[]).map(x=><li key={x}>{x}</li>)}</ul>:<p>None listed.</p>}</section>)}<h3>Limited</h3>{p.limited.length?<ul>{p.limited.map((x,i)=><li key={i}>{String(x.feature)}{x.limitCounterKey?` · ${String(x.limitCounterKey)}`:''}</li>)}</ul>:<p>None listed.</p>}<h3>Recorded usage limits</h3>{p.limits.length?<ul>{p.limits.map((x,i)=><li key={i}>{String(x.counterKey)} · {String(x.maxCount)} / {String(x.period)}</li>)}</ul>:<p>No usage limits are listed in this profile.</p>}</>}</section><section className={styles.panel}><h2>Recorded usage</h2>{usage.kind!=='success'?<ReadState kind={usage.kind}/>:!u?<ReadState kind="invalid_payload"/>:u.length?<ol className={styles.timeline}>{u.map(x=><li key={String(x.counterId)}><h3>{String(x.counterKey)}</h3><p>{String(x.count)} recorded · {String(x.period)}</p><p>{String(x.periodStart)} → {String(x.periodEnd)}</p></li>)}</ol>:<p>No usage counters are recorded.</p>}</section></div><section className={styles.panel}><h2>Recent access decisions</h2><p>These are recorded decisions, not a permission override. Each protected operation is checked again by the service.</p>{decisions.kind!=='success'?<ReadState kind={decisions.kind}/>:!d?<ReadState kind="invalid_payload"/>:d.length?<ol className={styles.timeline}>{d.map(x=><li key={String(x.decisionId)}><h3>{String(x.feature)} · {String(x.accessLevel)}</h3><p>{String(x.reasonCode)} · {String(x.decidedAt)}</p><p>Recorded usage: {x.currentUsage===null?'Not supplied':String(x.currentUsage)} · Limit: {x.limitMax===null?'Not supplied':String(x.limitMax)}</p></li>)}</ol>:<p>No recent access decisions were returned.</p>}</section></>;
}
export async function CommercialPage({mode}:{mode:'billing'|'access'}){const session=await requireAuthenticatedSession(`/settings/${mode}`);return <OperationalChrome session={session}><header className={styles.title}><div><h1>{mode==='billing'?'Know where your plan stands.':'Understand your access.'}</h1><p>{mode==='billing'?'Billing and payment state, read from your account. A redirect or return URL never activates access.':'Your recorded entitlement profile, usage and recent decisions, without local permission calculations.'}</p></div></header><SettingsNav/>{mode==='billing'?<Billing/>:<Access/>}<a className={styles.button} href={`/settings/${mode}`}>Read current account state</a></OperationalChrome>;}
