import Link from 'next/link';
import {requireAuthenticatedSession} from '../../lib/auth/server';
import {OperationalChrome} from '../../components/app/OperationalChrome';
import {RouteLink} from '../../components/public/RouteLink';
import {SignOut} from './SignOut';
import styles from '../../components/app/Operational.module.css';
const destinations=[['/settings/profile','Profile & identity','Your server-supplied identity and account status.'],['/settings/security','Account security','Sign out and recover existing credentials.']] as const;
export async function SettingsPage({mode}:{mode:'hub'|'profile'|'security'}) {
 const path=mode==='hub'?'/settings':`/settings/${mode}`;
 const session=await requireAuthenticatedSession(path),user=session.user;
 return <OperationalChrome session={session}><header className={styles.title}><div><h1>{mode==='hub'?'Your account, considered.':mode==='profile'?'Identity & continuity.':'Keep access deliberate.'}</h1><p>{mode==='hub'?'Review the identity and access that hold your workspace together.':mode==='profile'?'Identity comes from your sign-in service. These fields are read-only.':'Recovery and session exit, with no unsupported security controls.'}</p></div></header><nav className={styles.tabs} aria-label="Account settings"><RouteLink href="/settings">Account</RouteLink>{destinations.map(([href,label])=><RouteLink key={href} href={href}>{label}</RouteLink>)}</nav>
 {mode==='hub'?<ol className={styles.timeline}>{destinations.map(([href,label,copy])=><li key={href}><h2><Link href={href}>{label} ↗</Link></h2><p>{copy}</p></li>)}</ol>:mode==='profile'?<div className={styles.split}><section className={styles.panel}><h2>Signed-in identity</h2><dl className={styles.identityFields}>{[['Name',user.name??'Not supplied'],['Email',user.email??'Not supplied'],['Role',user.role],['Session plan label',user.planTier],['Onboarding recorded',user.onboardingCompletedAt??'Not completed']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p>A session plan label is not an authorization decision. Every protected capability is checked by the service.</p></section><aside className={styles.panel}><h2>Account continuity</h2><p>Changing your name, email or avatar is not supported by the current account contract.</p>{!user.onboardingCompletedAt&&<Link className={styles.button} href="/onboarding">Review onboarding</Link>}<SignOut/></aside></div>:<div className={styles.split}><section className={styles.panel}><h2>Existing credentials</h2><p>If you use a password, request a recovery link to change it. Google-only accounts should use Google account recovery.</p><Link className={styles.button} href="/forgot-password">Recover credentials ↗</Link></section><section className={styles.panel}><h2>This session</h2><p>Session expiry supplied by your sign-in service:</p><time dateTime={session.expires}>{session.expires}</time><SignOut/><p>Device listings, other-session termination and MFA setup are not supported here.</p></section></div>}
 </OperationalChrome>;
}
