import Link from 'next/link';
import {requireAuthenticatedSession} from '../../lib/auth/server';
import {readOwnedOperation} from '../../lib/api/owned-read';
import {OperationalChrome} from '../../components/app/OperationalChrome';
import {ReadState} from '../../components/app/ReadState';
import {RouteLink} from '../../components/public/RouteLink';
import {Modal} from '../../components/primitives/Modal';
import {envelope} from '../workspace/projection';
import {watchProjection,positionProjection,actionProjection,projectList,snapshotProjection,replayProjection} from './projection';
import {entityActions} from './operations';
import {PortfolioMutations} from './PortfolioMutations';
import ui from '../../components/app/Operational.module.css';
import styles from './Portfolio.module.css';
type View='overview'|'watchlist'|'positions'|'actions';
type Watch=NonNullable<ReturnType<typeof watchProjection>>;type Position=NonNullable<ReturnType<typeof positionProjection>>;type Action=NonNullable<ReturnType<typeof actionProjection>>;
const pathFor=(view:View)=>view==='overview'?'/portfolio':`/portfolio/${view}`;
const shown=(value:unknown)=>value===null?'Not recorded':Array.isArray(value)?value.join(' · ')||'None recorded':String(value);
function Facts({value,labels}:{value:Record<string,unknown>;labels:readonly(readonly[string,string])[]}){return <dl className={styles.details}>{labels.map(([key,label])=><div key={key}><dt>{label}</dt><dd>{shown(value[key])}</dd></div>)}</dl>;}
function Watchlist({items}:{items:Watch[]}){return items.length?<table className={styles.ledger}><caption>Watchlist records</caption><thead><tr>{['Market','Priority','Recorded status','Thesis health','Updated'].map(v=><th key={v} scope="col">{v}</th>)}</tr></thead><tbody>{items.map(v=><tr key={v.entryId}><td data-label="Market"><Link href={`/portfolio/watchlist?selected=${encodeURIComponent(v.entryId)}#record`}>{v.asset} · {v.timeframe} ↗</Link></td><td data-label="Priority"><span className={styles.priority} data-priority={v.priority}>{v.priority}</span></td><td data-label="Recorded status">{v.status.replaceAll('_',' ')}</td><td data-label="Thesis health">{v.thesisHealth}</td><td data-label="Updated"><time dateTime={v.updatedAt}>{v.updatedAt}</time></td></tr>)}</tbody></table>:<section className={ui.state}><h2>No portfolio watchlist entries returned.</h2><p>Record a watchlist entry to keep its thesis, priority and lifecycle together. Account tracked markets remain a separate preference.</p></section>;}
function Positions({items,snapshot=false}:{items:Position[];snapshot?:boolean}){return items.length?<table className={styles.ledger}><caption>Position records</caption><thead><tr>{['Market','Direction / status','Recorded entry','Recorded size','Recorded stop','Thesis health'].map(v=><th key={v} scope="col">{v}</th>)}</tr></thead><tbody>{items.map(v=><tr key={v.positionId}><td data-label="Market"><Link href={`/portfolio/positions?selected=${encodeURIComponent(v.positionId)}#record`}>{v.asset} · {v.timeframe} ↗</Link></td><td data-label="Direction / status">{v.direction} · {v.status}</td><td data-label="Recorded entry">{shown(v.entryPrice)}</td><td data-label="Recorded size">{shown(v.size)}</td><td data-label="Recorded stop">{shown(v.stopLoss)}</td><td data-label="Thesis health">{v.thesisHealth}</td></tr>)}</tbody></table>:<section className={ui.state}><h2>{snapshot?'No position records in this saved snapshot.':'No open or reducing positions returned.'}</h2><p>{snapshot?'This is the saved snapshot window, not proof of current activity.':'This list does not establish that proposed or closed records are absent. Use a saved record ID to read one directly.'}</p></section>;}
function Actions({items,snapshot=false}:{items:Action[];snapshot?:boolean}){return items.length?<ol className={styles.queue}>{items.map(v=><li key={v.actionId}><div><span className={styles.priority} data-priority={v.priority}>{v.priority} priority</span><p>{v.kind.replaceAll('_',' ')} · {v.status}</p></div><div><h2>{v.headline}</h2><p>{v.rationale}</p><p>{v.asset===null?'No market supplied':v.asset} · {v.timeframe===null?'No timeframe supplied':v.timeframe}</p></div><Link href={`/portfolio/actions?selected=${encodeURIComponent(v.actionId)}#record`}>Review item ↗</Link></li>)}</ol>:<section className={ui.state}><h2>{snapshot?'No action items in this saved snapshot.':'No open action items returned.'}</h2><p>{snapshot?'No actions were included in the recorded snapshot window.':'Completed and dismissed records are not included in this queue. Reading it does not generate recommendations.'}</p></section>;}
function EntityDetail({value,kind,replay,returnPath}:{value:Watch|Position|Action;kind:'entry'|'position'|'action';replay:unknown;returnPath:string}){
 const id='entryId'in value?value.entryId:'positionId'in value?value.positionId:value.actionId;
 const health='thesisHealth'in value?value.thesisHealth:undefined,history=replayProjection(replay,kind==='entry'?'watchlist_entry':kind==='position'?'position':'action_item',id);
 const labels:readonly(readonly[string,string])[]=kind==='entry'?[[ 'asset','Market'],['timeframe','Timeframe'],['priority','Priority'],['status','Recorded status'],['thesisHealth','Recorded thesis health'],['note','Note'],['createdAt','Created'],['updatedAt','Updated']]:kind==='position'?[[ 'asset','Market'],['timeframe','Timeframe'],['direction','Direction'],['status','Recorded status'],['entryPrice','Recorded entry'],['size','Recorded size'],['stopLoss','Recorded stop'],['takeProfitLevels','Recorded targets'],['thesisHealth','Recorded thesis health'],['openedAt','Opened'],['closedAt','Closed'],['updatedAt','Updated'],['note','Note']]:[[ 'headline','Headline'],['rationale','Rationale'],['kind','Action kind'],['priority','Priority'],['status','Recorded status'],['asset','Market'],['timeframe','Timeframe'],['createdAt','Created'],['updatedAt','Updated'],['completedAt','Completed'],['dismissedAt','Dismissed']];
 return <section className={styles.detail} id="record"><p>Saved {kind==='entry'?'watchlist entry':kind} · {id}</p><h2>{'headline'in value?value.headline:`${value.asset} · ${value.timeframe}`}</h2><Facts value={value} labels={labels}/><h3>Recorded relationships</h3><Facts value={value} labels={kind==='action'?[[ 'linkedEntryId','Watchlist entry ID'],['linkedPositionId','Position ID'],['linkedReasoningRunId','Reasoning run ID'],['linkedNotificationDecisionId','Notification decision ID']]:[[ 'linkedReasoningRunId','Reasoning run ID'],['linkedSnapshotId','Snapshot ID'],['linkedDriftId','Drift ID']]}/>{value.linkedJournalCaseId?<p><Link href={`/journal/${encodeURIComponent(value.linkedJournalCaseId)}`}>Read linked journal case ↗</Link></p>:<p>No journal case linked.</p>}<PortfolioMutations key={id} offers={entityActions(kind,value.status,health)} id={id} status={value.status} health={health} returnPath={returnPath}/><Modal label="View entity history" title="Entity history">{history===null?<ReadState kind="invalid_payload"/>:history.length?<ol className={styles.history}>{history.map(v=><li key={v.revisionId}><time dateTime={v.changedAt}>{v.changedAt}</time><h3>{v.revisionType.replaceAll('_',' ')}</h3><p>{v.summary}</p></li>)}</ol>:<p>No recorded revisions returned for this entity.</p>}</Modal></section>;
}
export async function PortfolioPage({view,selected}:{view:View;selected?:string}){
 const path=pathFor(view),session=await requireAuthenticatedSession(path),key=()=>({idempotency:{key:crypto.randomUUID()}});
 const result=view==='overview'?await readOwnedOperation('GET /api/portfolio/snapshot/current',{}):view==='watchlist'?await readOwnedOperation('GET /api/portfolio/watchlist',key()):view==='positions'?await readOwnedOperation('GET /api/portfolio/positions',key()):await readOwnedOperation('GET /api/portfolio/actions',key());
 let content;
 if(result.kind!=='success')content=<ReadState kind={result.kind}/>;
 else {const data=envelope(result.value);
  if(view==='overview'){const v=snapshotProjection(data?.snapshot);content=data?.snapshot===null?<section className={ui.state}><h2>No portfolio snapshot has been saved.</h2><p>Choose generation explicitly when you want the service to create a new view. Reading this page does not create one.</p></section>:!v?<ReadState kind="invalid_payload"/>:<><p className={styles.context}>Saved snapshot {v.snapshotId} · <time dateTime={v.generatedAt}>{v.generatedAt}</time>. This is a recorded view, not live pricing or proof of current freshness.</p><dl className={styles.counts}>{[['Active watchlist',v.counts.activeWatchlistCount],['Active positions',v.counts.activePositionCount],['Weakening theses',v.counts.weakeningThesisCount],['Invalidated theses',v.counts.invalidatedThesisCount],['Open actions',v.counts.openActionCount],['Critical actions',v.counts.criticalActionCount]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><Watchlist items={v.entries}/><Positions items={v.positions} snapshot/><Actions items={v.actions} snapshot/><Modal label="Snapshot detail" title="Saved snapshot detail"><Facts value={v} labels={[[ 'snapshotId','Snapshot ID'],['generatedAt','Generated'],['createdAt','Created']]}/><p>All counts and records are returned by the service; totals are not recomputed here.</p></Modal></>;}
  else if(view==='watchlist'){const v=projectList(data?.entries,watchProjection);content=v?<Watchlist items={v}/>:<ReadState kind="invalid_payload"/>;}
  else if(view==='positions'){const v=projectList(data?.positions,positionProjection);content=v?<Positions items={v}/>:<ReadState kind="invalid_payload"/>;}
  else {const v=projectList(data?.actions,actionProjection);content=v?<Actions items={v}/>:<ReadState kind="invalid_payload"/>;}
 }
 let detail;
 if(selected&&view!=='overview'){
  const selectedResult=view==='watchlist'?await readOwnedOperation('GET /api/portfolio/watchlist/{entryId}',{...key(),path:{entryId:selected}}):view==='positions'?await readOwnedOperation('GET /api/portfolio/positions/{positionId}',{...key(),path:{positionId:selected}}):await readOwnedOperation('GET /api/portfolio/actions/{actionId}',{...key(),path:{actionId:selected}});
  if(selectedResult.kind!=='success')detail=<section id="record"><ReadState kind={selectedResult.kind}/></section>;
  else {const data=envelope(selectedResult.value),v=view==='watchlist'?watchProjection(data?.entry):view==='positions'?positionProjection(data?.position):actionProjection(data?.action);const returnedId=v?('entryId'in v?v.entryId:'positionId'in v?v.positionId:v.actionId):null;detail=v&&returnedId===selected?<EntityDetail value={v} kind={view==='watchlist'?'entry':view==='positions'?'position':'action'} replay={data?.replay} returnPath={`${path}?selected=${encodeURIComponent(selected)}#record`}/>:<ReadState kind="invalid_payload"/>;}
 }
 const title={overview:'Keep context beside the record.',watchlist:'A watchlist with a thesis.',positions:'Positions, as recorded.',actions:'Keep the next review in view.'};
 return <OperationalChrome session={session}><header className={styles.intro}><div><h1>{title[view]}</h1><p>{view==='overview'?'Portfolio entities, recorded thesis health and a service-owned action queue.':view==='watchlist'?'Priority, thesis health and lifecycle for each portfolio entry. This is distinct from account tracked markets.':view==='positions'?'The current list includes open and reducing records. Proposed, closed and canceled records can be read by their saved ID.':'Open actions in the order returned by the service. Completing an item records that action; it does not execute a trade.'}</p></div><aside>ELCEO is decision support. These records are not a brokerage balance, execution feed or live valuation.</aside></header><nav className={ui.tabs} aria-label="Portfolio">{(['overview','watchlist','positions','actions'] as const).map(v=><RouteLink key={v} href={pathFor(v)}>{v==='overview'?'Overview':v==='actions'?'Action queue':v==='positions'?'Positions':'Watchlist'}</RouteLink>)}</nav><PortfolioMutations offers={[view==='overview'?'snapshot':view==='watchlist'?'watch-create':view==='positions'?'position-create':'action-create']} returnPath={path}/>{content}{view==='overview'?<p className={styles.context}>A separate passive attention summary is not available in this view. The saved snapshot above remains the source for its recorded counts and entities.</p>:<><p className={styles.context}>{view==='positions'?'The service returns up to 50 open and 50 reducing records.':view==='watchlist'?'This view shows the current returned window of up to 50 watchlist records.':'This queue shows the current returned window of up to 50 open actions.'} Absence from this window is not proof that a record does not exist.</p><form action={path} className={styles.lookup}><label className={styles.field}>Read a saved {view==='watchlist'?'entry':view==='positions'?'position':'action'} by ID<input name="selected" required autoComplete="off" defaultValue={selected??''}/></label><button className={styles.action}>Read saved record</button></form>{detail}</>}</OperationalChrome>;
}
