import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {project,matchesContext} from '../../features/admin/projection.ts';import {system,control,transition,quality} from '../../features/admin/schemas.ts';import {parseCommandBody} from '../../features/admin/commands.ts';
const fixture=(name:string)=>JSON.parse(readFileSync(new URL(`../../../../contracts/backend/mocks/${name}.json`,import.meta.url),'utf8'));
test('canonical admin and super-admin mock projections remain exact, without editing fixtures',()=>{const a=fixture('admin-system-summary').data.summary;assert.deepEqual(project(a,system),a);const b=fixture('super-admin-control-snapshot').data.snapshot;assert.deepEqual(project(b,control),b);});
test('null previous commercial states remain null; unknown is never zero',()=>{const v={transitionId:'transition',subjectId:'subject',providerKind:'manual_test',previousPlanKind:null,nextPlanKind:'free',previousAccountState:null,nextAccountState:'active',decisionCode:'free_default_ok',severity:'info',rationale:'Recorded source decision',decidedAt:'now',restrictedAccess:false,recoveredAccess:false,private:'secret'};const projected=project(v,transition);assert(projected&&typeof projected==='object'&&!Array.isArray(projected));assert.equal(projected.previousPlanKind,null);assert(!JSON.stringify(projected).includes('secret'));assert.equal(project({...v,recoveredAccess:'false'},transition),undefined);});
test('quality is server-projected and malformed numeric authority is rejected',()=>{const q={payloadId:'p',evidenceTypeId:'e',evidenceClass:'market_news',providerId:'provider',region:'global',observedAt:'now',evaluatedAt:'now',provenanceKind:'fixture',freshnessStatus:'stale',conflictStatus:'unknown',usabilityStatus:'warning',asset:null,sourceQualityScore:0,freshnessScore:0,completenessScore:0,conflictScore:0,finalQualityScore:0,reasons:[]};assert.deepEqual(project(q,quality),q);assert.equal(project({...q,finalQualityScore:null},quality),undefined);assert.equal(project({...q,finalQualityScore:Infinity},quality),undefined);});
test('command fields reject injected authority, unsupported modes and fabricated verification',()=>{assert.equal(parseCommandBody('gift',{userId:'u',duration:'two_weeks',stepUpChallengeId:'c',verified:true}),null);assert.equal(parseCommandBody('replay',{runId:'r',replayMode:'production_live'}),null);assert.equal(parseCommandBody('challenge',{actionKind:'focus_plan_gift',targetUserId:'u',providerKind:'fixture_test_only'}),null);assert.equal(parseCommandBody('entitlementState',{subjectId:'u',accountState:'banned'}),null);assert.equal(parseCommandBody('renew',{subjectId:'u',nextPeriodStart:'nonsense',nextPeriodEnd:'nonsense'}),null);});

test('wrong nested subject/market is rejected',()=>{assert.equal(matchesContext({snapshot:{subjectId:'other'}},{subjectId:'selected'}),false);assert.equal(matchesContext({asset:'eur_usd'},{asset:'xau_usd'}),false);});
